supply-block-chains-master/app/views/home.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app.forms import LoginForm, RegistrationForm
from flask_login import current_user, login_user, logout_user, login_required
from app.models import User
from ..services.user_services import register_user
from ..services.transaction_services import get_user_insights
from ..constants import RETAILER, SUPPLIER, COURIER


home = Blueprint('home', __name__)


@home.route('/')
@login_required
def dashboard():
    initiated_tx = get_user_insights(current_user)
    return render_template('home/index.html', title='Dashboard', number=initiated_tx)


@home.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('home.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('home.dashboard'))
    return render_template('home/login.html', form=form)


@home.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home.login'))


@home.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home.dashboard'))
    form = RegistrationForm()
    roles = [RETAILER, SUPPLIER, COURIER]
    form.user_role.choices = [(x, x) for x in roles]
    if form.validate_on_submit():
        register_user(form)
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('home.login'))
    return render_template('home/register.html', title='Register', form=form)

supply-block-chains-master/app/templates/home/index.html
{% extends "_layout.html" %}

{% block content %}

    <!-- WELCOME-->
    <section class="welcome p-t-20">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">Welcome back
                        <span>to Albertson's Blockchain!</span>
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
        </div>
    </section>
    <!-- END WELCOME-->

    <!-- STATISTIC-->
    <section class="statistic statistic2">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-3">
                    <div class="statistic__item statistic__item--green">
                        <h2 class="number">{{ number }}</h2>
                        <span class="desc">members online</span>
                        <div class="icon">
                            <i class="zmdi zmdi-account-o"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="statistic__item statistic__item--orange">
                        <h2 class="number">388,688</h2>
                        <span class="desc">items sold</span>
                        <div class="icon">
                            <i class="zmdi zmdi-shopping-cart"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="statistic__item statistic__item--blue">
                        <h2 class="number">1,086</h2>
                        <span class="desc">this week</span>
                        <div class="icon">
                            <i class="zmdi zmdi-calendar-note"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="statistic__item statistic__item--red">
                        <h2 class="number">$1,060,386</h2>
                        <span class="desc">total earnings</span>
                        <div class="icon">
                            <i class="zmdi zmdi-money"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END STATISTIC-->

    <!-- STATISTIC CHART-->
    <section class="statistic-chart">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="title-5 m-b-35">statistics</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-lg-4">
                    <!-- CHART-->
                    <div class="statistic-chart-1">
                        <h3 class="title-3 m-b-30">chart</h3>
                        <div class="chart-wrap">
                            <canvas id="widgetChart5"></canvas>
                        </div>
                        <div class="statistic-chart-1-note">
                            <span class="big">10,368</span>
                            <span>/ 16220 items sold</span>
                        </div>
                    </div>
                    <!-- END CHART-->
                </div>
                <div class="col-md-6 col-lg-4">
                    <!-- TOP CAMPAIGN-->
                    <div class="top-campaign">
                        <h3 class="title-3 m-b-30">top campaigns</h3>
                        <div class="table-responsive">
                            <table class="table table-top-campaign">
                                <tbody>
                                    <tr>
                                        <td>1. Australia</td>
                                        <td>$70,261.65</td>
                                    </tr>
                                    <tr>
                                        <td>2. United Kingdom</td>
                                        <td>$46,399.22</td>
                                    </tr>
                                    <tr>
                                        <td>3. Turkey</td>
                                        <td>$35,364.90</td>
                                    </tr>
                                    <tr>
                                        <td>4. Germany</td>
                                        <td>$20,366.96</td>
                                    </tr>
                                    <tr>
                                        <td>5. France</td>
                                        <td>$10,366.96</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END TOP CAMPAIGN-->
                </div>
                <div class="col-md-6 col-lg-4">
                    <!-- CHART PERCENT-->
                    <div class="chart-percent-2">
                        <h3 class="title-3 m-b-30">chart by %</h3>
                        <div class="chart-wrap">
                            <canvas id="percent-chart2"></canvas>
                            <div id="chartjs-tooltip">
                                <table></table>
                            </div>
                        </div>
                        <div class="chart-info">
                            <div class="chart-note">
                                <span class="dot dot--blue"></span>
                                <span>products</span>
                            </div>
                            <div class="chart-note">
                                <span class="dot dot--red"></span>
                                <span>Services</span>
                            </div>
                        </div>
                    </div>
                    <!-- END CHART PERCENT-->
                </div>
            </div>
        </div>
    </section>
    <!-- END STATISTIC CHART-->



{% endblock %}

supply-block-chains-master/app/templates/home/login.html
{% extends "_loginlayout.html" %}

{% block content %}

    <form action="" method="post">
    {{ form.hidden_tag() }}
        <div class="form-group">
            <label>Username</label>
            {{ form.username(size=32, class_='au-input au-input--full', placeholder='Username') }}
            {% if form.username.errors %}
              <br>
              {% for error in form.username.errors %}
                <span style="color:red">[{{error}}]</span>
              {% endfor %}
            {% endif %}
        </div>
        <div class="form-group">
            <label>Password</label>
            {{ form.password(size=32, class_='au-input au-input--full', placeholder='Password') }}
            {% if form.password.errors %}
                <br>
                {% for error in form.password.errors %}
                    <span style="color:red">[{{error}}]</span>
                {% endfor %}
            {% endif %}
        </div>

        <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">sign in</button>

    </form>
    <div class="register-link">
        <p>
            Don't you have account?
            <a href="{{ url_for('home.register') }}">Sign Up Here</a>
        </p>
    </div>

{% endblock %}

supply-block-chains-master/app/templates/home/register.html
{% extends "_loginlayout.html" %}

{% block content %}

<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <label>Company</label>
        {{ form.company(size=32, class_='au-input au-input--full', placeholder='Company') }}
        {% if form.company.errors %}
          <br>
          {% for error in form.company.errors %}
            <span style="color:red">[{{error}}]</span>
          {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        <label>Company Role</label>
        {{ form.user_role(class_='form-control') }}
        {% if form.user_role.errors %}
          <br>
          {% for error in form.user_role.errors %}
            <span style="color:red">[{{error}}]</span>
          {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        <label>Username</label>
        {{ form.username(size=32, class_='au-input au-input--full', placeholder='Username') }}
        {% if form.username.errors %}
          <br>
          {% for error in form.username.errors %}
            <span style="color:red">[{{error}}]</span>
          {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        <label>Email Address</label>
        {{ form.email(size=32, class_='au-input au-input--full', placeholder='Email') }}
        {% if form.email.errors %}
          <br>
          {% for error in form.email.errors %}
            <span style="color:red">[{{error}}]</span>
          {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        <label>Password</label>
        {{ form.password(size=32, class_='au-input au-input--full', placeholder='Password') }}
        {% if form.password.errors %}
          <br>
          {% for error in form.password.errors %}
            <span style="color:red">[{{error}}]</span>
          {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        <label>Confirm Password</label>
        {{ form.password2(size=32, class_='au-input au-input--full', placeholder='Confirm Password') }}
        {% if form.password2.errors %}
          <br>
          {% for error in form.password2.errors %}
            <span style="color:red">[{{error}}]</span>
          {% endfor %}
        {% endif %}
    </div>

    <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">register</button>

</form>
<div class="register-link">
    <p>
        Already have account?
        <a href="{{ url_for('home.login') }}">Sign In</a>
    </p>
</div>

{% endblock %}