supply-block-chains-master/app/views/transaction.py
import datetime

from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from ..forms import CreateTransactionForm
from ..services.transaction_object import Transaction
from ..services.transaction_services import fetch_user_transactions, post_transaction, get_details
from ..services.user_services import get_users_in_role
from ..constants import INITIATED, SUPPLIER, RETAILER, COURIER, TRACKED
from ..utils import timestamp_to_string
import json

transaction = Blueprint('transaction', __name__)


@transaction.route('/transaction/list', methods=['GET'])
@login_required
def all_transactions():
    tx = fetch_user_transactions(current_user)
    for tr in tx:
        detail, tracking = get_details(tr['node_id'])
        tr['status'] = detail['current_status']
        tr['timestamp'] = detail['timestamp']
        tr['courier'] = detail['courier']
    can_order = (current_user.user_role == RETAILER)
    return render_template('transaction/list.html', title='Transactions', transactions=tx, can_order=can_order,
                           readable_time=timestamp_to_string)


@transaction.route('/transaction/new', methods=['GET', 'POST'])
@login_required
def create_transaction():
    message = ''
    form = CreateTransactionForm()
    form.supplier.choices = [(users.company, users.company) for users in get_users_in_role(SUPPLIER)]
    if form.validate_on_submit():
        new_tx = Transaction(block_type=INITIATED, actor_public_key=current_user.public_key,
                             actor_private_key=current_user.private_key, actor=current_user.company,
                             supplier=form.supplier.data, item=form.item.data, quantity=form.quantity.data)
        new_tx.signature = new_tx.sign_transaction()
        try:
            result = post_transaction(new_tx)
        except:
            result = False
        if result:
            flash('Order has been successfully created.')
            return redirect(url_for('transaction.all_transactions'))
        else:
            message = 'An error occurred.'
    return render_template('transaction/create.html', title='Create', form=form, message=message)


@transaction.route('/transaction/details/<order>', methods=['GET'])
@login_required
def view_transaction(order):
    details, tracking = get_details(order)
    can_act = (details['current_status'] == 'pending') and (details['origin'] == current_user.company)
    non_traking_options = ['pending', 'declined', 'received']
    can_track = (details['current_status'] not in non_traking_options)
    role = {
        'retailer': can_track and current_user.user_role == RETAILER,
        'supplier': can_track and details['courier'] == '' and current_user.user_role == SUPPLIER,
        'courier': can_track and details['courier'] == current_user.company
    }
    couriers = [c.company for c in get_users_in_role(COURIER) if details['courier'] != c.company]
    return render_template('transaction/details.html', title='Details', details=details, tracking=tracking,
                           readable_time=timestamp_to_string, can_act=can_act, role=role, couriers=couriers)


@transaction.route('/transaction/update_tracking', methods=['POST'])
@login_required
def update_tracking():
    data = request.get_json()

    required = ['order', 'status', 'courier']
    if not all(k in data for k in required):
        return 'Missing Values', 400

    new_tx = Transaction(block_type=TRACKED, actor_public_key=current_user.public_key,
                         actor_private_key=current_user.private_key, actor=current_user.company,
                         node_id=data['order'], status=data['status'], courier=data['courier'])
    new_tx.signature = new_tx.sign_transaction()
    try:
        result = post_transaction(new_tx)
    except:
        result = False
    if result:
        flash('Order has been updated successfully.')
        return jsonify({'message': 'Successful'}), 200
    else:
        return 'An error occurred.', 400

supply-block-chains-master/app/templates/transaction/create.html
{% extends "_layout.html" %}

{% block content %}

<div class="col-lg-6">
    <div class="card">
        <div class="card-header">
            <strong>Create an order here</strong>
        </div>
        <form action="" method="post" class="form-horizontal">
        <div class="card-body card-block">
            {{ form.hidden_tag() }}
            <div class="row form-group">
                <div class="col col-md-3">
                    <label class=" form-control-label">Order by:</label>
                </div>
                <div class="col-12 col-md-9">
                    <p class="form-control-static">{{ current_user.company }}</p>
                </div>
            </div>
            <div class="row form-group">
                <div class="col col-md-3">
                    <label class=" form-control-label">Supplier</label>
                </div>
                <div class="col-12 col-md-9">
                    {{ form.supplier(class_='form-control') }}
                    {% if form.supplier.errors %}
                      <br>
                      {% for error in form.supplier.errors %}
                        <span style="color:red">[{{error}}]</span>
                      {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="row form-group">
                <div class="col col-md-3">
                    <label class=" form-control-label">Item Description</label>
                </div>
                <div class="col-12 col-md-9">
                    {{ form.item(class_='form-control', placeholder='Enter the items you want') }}
                    {% if form.item.errors %}
                      <br>
                      {% for error in form.item.errors %}
                        <span style="color:red">[{{error}}]</span>
                      {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="row form-group">
                    <div class="col col-md-3">
                        <label class=" form-control-label">Quantity</label>
                    </div>
                    <div class="col-12 col-md-9">
                        {{ form.quantity(class_='form-control', placeholder='Enter the quantity') }}
                        {% if form.quantity.errors %}
                          <br>
                          {% for error in form.quantity.errors %}
                            <span style="color:red">[{{error}}]</span>
                          {% endfor %}
                        {% endif %}
                    </div>
                </div>
        <p class="text-danger">
            {{ message if message != '' }}
        </p>
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-primary btn-sm">
                <i class="fa fa-dot-circle-o"></i> Submit
            </button>
            <button type="reset" class="btn btn-danger btn-sm">
                <i class="fa fa-ban"></i> Reset
            </button>
        </div>
        </form>
    </div>
</div>

{% endblock %}

supply-block-chains-master/app/templates/transaction/details.html
{% extends "_layout.html" %}

{% block content %}

    <section class="p-t-20">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                Transaction Details
                            </h4>
                        </div>
                        <div class="card-body">
                            <p>
                                <b>Order Number</b> : {{ details.order_number }}
                            </p>
                            <p>
                                <b>Origin</b> : {{ details.origin }}
                            </p>
                            <p>
                                <b>Destination</b> : {{ details.destination }}
                            </p>
                            <p>
                                <b>Item Description</b> : {{ details.item }}
                            </p>
                            <p>
                                <b>Quantity</b> : {{ details.quantity }}
                            </p>
                            <p>
                                <b>Status</b> : {{ details.current_status }}
                            </p>
                            <p>
                                <b>Date/Time</b> : {{ readable_time(details.timestamp) }}
                            </p>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-default" href="{{ url_for('transaction.all_transactions') }}">
                                <i class="fa fa-chevron-circle-left"></i> Go Back
                            </a>
                            {% if can_act %}
                                <button class="btn btn-success pull-right btn-action" data-status="approved">
                                    Accept
                                </button>
                                <button class="btn btn-danger pull-right btn-action" data-status="declined">
                                    Decline
                                </button>
                            {% endif %}
                            {% if role.retailer %}
                                <button class="btn btn-success pull-right btn-action" data-status="received">
                                    Confirm Order Received <i class="fa fa-check-circle"></i>
                                </button>
                            {% endif %}
                            {% if role.supplier or role.courier %}
                                <button class="btn btn-info pull-right btn-action" data-status="update">
                                    Update Tracking <i class="fa fa-info-circle"></i>
                                </button>
                                {% if role.supplier %}
                                    <button class="btn btn-info pull-right btn-action" data-status="shipped">
                                        Ship Order <i class="fa fa-info-circle"></i>
                                    </button>
                                {% endif %}
                                {% if role.courier %}
                                    <button class="btn btn-info pull-right btn-action" data-status="transferred">
                                        Transfer Order <i class="fa fa-info-circle"></i>
                                    </button>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                <div class="accordion" id="trackDiv">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">
                                <button class="btn btn-default btn-sm" type="button" data-toggle="collapse" data-target="#trackingInfo" aria-expanded="true" aria-controls="trackingInfo">
                                  View Tracking Information
                                </button>
                            </h5>
                        </div>
                        <div id="trackingInfo" class="collapse show" aria-labelledby="trackingInfo" data-parent="#trackDiv">
                            <div class="card-body">
                            {% for tr in tracking %}
                                {% if tr.courier != '' %}
                                <p>
                                    Courier : {{ tr.courier }}
                                </p>
                                {% endif %}
                                <p>
                                    Status : {{ tr.status }}
                                </p>
                                <p>
                                    Actor : {{ tr.actor }}
                                </p>
                                <p>
                                    Timestamp : {{ readable_time(tr.timestamp) }}
                                </p>
                                <hr>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Modal -->
    <div class="modal modal-alert fade" id="basicModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
      <div class="modal-dialog">

        <div class="modal-content">

          <div class="modal-header">
            <div class="modal-title col-md-10">Update Order Tracking Information</div>
            <button type="button" class="close col-md-2" data-dismiss="modal" aria-hidden="true">&times;</button>
          </div>

          <div class="modal-body">

            <form>
                <input type="hidden" value="{{ details.order_number }}" id="orderId">
                <input type="hidden" id="oStatus">
                <input type="hidden" id="oCourier" value="{{ details.courier }}">
                <input type="hidden" id="oAction">

                <p id="confirmText">

                </p>

                <div class="row" id="order-status-div">
                  <label class="col-sm-12">Order Status:</label>
                  <div class="col-sm-12">
                    <input type="text" id="orderStatus" class="form-control">
                  </div>
                </div>

                <div class="row" id="order-courier-div">
                  <label class="col-sm-12">Select Courier:</label>
                  <div class="col-sm-12">
                      <select id="courierSelect">
                          <option value="">- Select Courier -</option>
                          {% for courier in couriers %}
                              <option value="{{ courier }}">{{ courier }}</option>
                          {% endfor %}
                      </select>
                  </div>
                </div>

            </form>
            <p id="errorTxt" class="text-danger"></p>

          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <button type="button" id="button_confirm" class="btn btn-success">Confirm</button>
          </div>

        </div>

      </div>
    </div>

{% endblock %}


{% block scripts %}

    <script type="text/javascript">

        $(document).ready(function () {

            $('.btn-action').on('click', function(){

                var status = $(this).attr('data-status');
                init_modal(status);

            })

            $('#button_confirm').on('click', function () {

                var action = $('#oAction').val();
                var status = '';
                var courier = '';
                var valid =  '';

                if(action == '1'){
                    status = $('#oStatus').val();
                    courier = $('#oCourier').val();
                    valid = status ? true : '';
                }
                if(action == '2'){
                    status = $('#oStatus').val();
                    courier = $('#courierSelect').val();
                    valid = courier ? true : '';
                }
                if(action == '3'){
                    status = $('#orderStatus').val();
                    courier = $('#oCourier').val();
                    valid = status.trim() ? true : '';
                }

                if(valid){
                    {#alert('status : ' + status + '\ncourier : '+ courier);#}
                    update_info(status, courier)
                }else{
                    $('#errorTxt').text('Missing Values!')
                }

            })

            function init_modal(status){
                $('#order-status-div').hide();
                $('#order-courier-div').hide();
                $('#orderStatus').val('');
                $('#oAction').val('');
                $('#confirmText').text('')
                $('#errorTxt').text('')
                if(status == 'approved' || status == 'declined'){
                    $('#oStatus').val(status);
                    $('#confirmText').text('This order is about to be ' + status);
                    $('#oAction').val('1');
                    $('#basicModal').modal('show');
                }
                if(status == 'received'){
                    $('#oStatus').val(status);
                    $('#confirmText').text('I have received the order.');
                    $('#oAction').val('1');
                    $('#basicModal').modal('show');
                }
                if(status == 'shipped' || status == 'transferred'){
                    $('#oStatus').val(status);
                    $('#order-courier-div').show();
                    $('#oAction').val('2');
                    $('#basicModal').modal('show');
                }
                if(status == 'update'){
                    $('#order-status-div').show();
                    $('#oAction').val('3');
                    $('#basicModal').modal('show');
                }
            }


            function update_info(status, courier){
                var data = {
                      order: $('#orderId').val(),
                      status: status,
                      courier: courier
                }
                $.ajax({
                  url: "/transaction/update_tracking",
                  type: "POST",
                  dataType : 'json',
                  contentType: 'application/json',
                  data: JSON.stringify(data),
                  success: function(response){
                    location.reload(true)
                  },
                  error: function(error){
                    console.log(error);
                    $('#basicModal').modal('hide');
                    alert('Operation Failed! Please Try Again.')
                  }
                });
            }

        })

    </script>

{% endblock %}

supply-block-chains-master/app/templates/transaction/list.html
{% extends "_layout.html" %}

{% block content %}

    <!-- DATA TABLE-->
    <section class="p-t-20">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="title-5 m-b-35">All Transactions</h3>
                    <div class="table-data__tool">
                        <div class="table-data__tool-left">
                            <div class="rs-select2--light rs-select2--md">
                                <select class="js-select2" name="property">
                                    <option selected="selected">All</option>
                                    <option value="">Pending</option>
                                    <option value="">Approved</option>
                                    <option value="">Declined</option>
                                    <option value="">Shipped</option>
                                </select>
                                <div class="dropDownSelect2"></div>
                            </div>
                            <button class="au-btn-filter">
                                <i class="zmdi zmdi-filter-list"></i>filters</button>
                        </div>
                        <div class="table-data__tool-right">
                            {% if can_order %}
                            <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{{ url_for('transaction.create_transaction') }}">
                                <i class="zmdi zmdi-plus"></i>Create Order
                            </a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="table-responsive table-responsive-data2">
                        <table class="table table-data2">
                            <thead>
                                <tr>
                                    <th>Order No</th>
                                    <th>Origin</th>
                                    <th>Destination</th>
                                    <th>Courier</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>Date</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for tx in transactions %}
                                <tr class="tr-shadow">
                                    <td>{{ tx.node_id }}</td>
                                    <td>{{ tx.actor }}</td>
                                    <td>{{ tx.supplier }}</td>
                                    <td>{{ tx.courier }}</td>
                                    <td>{{ '{} - {}'.format(tx.item, tx.quantity) }}</td>
                                    <td>{{ tx.status }}</td>
                                    <td>{{ readable_time(tx.timestamp) }}</td>
                                    <td>
                                        <div class="table-data-feature">
                                            <a href="{{ url_for('transaction.view_transaction', order=tx.node_id) }}" class="item" data-toggle="tooltip" data-placement="top" title="Order Details">
                                                <i class="zmdi zmdi-more"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                <tr class="spacer"></tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
        <!-- END DATA TABLE-->

{% endblock %}